spring:
  application:
    name: wiremock_service_wm
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/, classpath:/wiremock/mappings/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/db2?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: neo.spider.admin
  configuration:
      map-underscore-to-camel-case: true
    
server:
  port: 8889

admin:
  id: admin
  password: '1234'
