version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  kafkaconsumer:
    image: neobnsrn5/kafkaconsumer:s1
    container_name: KafkaConsumer
    ports:
      - "18788:18788"
    depends_on:
      - kafka

  rabbitmqconsumer:
    image: neobnsrn5/rabbitconsumer:s1
    ports:
      - "18988:18988"
    depends_on:
      - rabbitmq