spring:
  application:
    name: transfer
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config:1234@localhost:9393



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:1234@localhost:8761/eureka
