spring:
  application:
    name: transfer
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config:1234@localhost:9393
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 1234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:1234@localhost:8761/eureka

management:
  httpexchanges:
    recording:
      enabled: true
  endpoints:
    web:
      exposure:
#        include: "*"
         include: health, info, metrics, prometheus
    jmx:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enable:
        all: true
    health:
      show-details: always
    prometheus:
      enabled: true  
    env:
      sensitive: false
      show-sensitive: true
  info:
    env:
      enabled: true
  web:
    base-path: /actuator
  metrics:
    enable:
      hikaricp: true
  