server:
  port: 8090

spring:
  application:
    name: transfer
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config:1234@localhost:9393
  cache:
    redis:
      ttl: 10000000  
  data:
    redis:
      host: localhost 
      # 레디스 돌릴 서버 호스트로 수정할 것
      # sudo vim /etc/redis/redis.conf
      # # 1) 모든 IP에서 접속 허용
      # bind 0.0.0.0
      # 2) 외부 접속 허용 (권장 비밀번호 설정)
      # requirepass your_password
      # 3) 포트 설정 (기본값 6379)
      # port 6379
      port: 6379  
      password:   
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  boot:
    admin:
      client:
        url: http://localhost:9000/adminPage

# 주석처리 한 부분은 config server의 prperties에 존재
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka:1234@localhost:8761/eureka

#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

#management:
#  httpexchanges:
#    recording:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
##        include: "*"
#        include: health, info, metrics, prometheus, busrefresh
#      base-path: /actuator
#  endpoint:
#    metrics:
#      enabled: true
#    health:
#      show-details: always
#    prometheus:
#      enabled: true
#    env:
#      enabled: true
#  info:
#    env:
#      enabled: true
#  metrics:
#    enable:
#      hikaricp: true
#
values:
  queue: example-queue
  exchange: example-exchange
  routingKey: example-routing-key
