server:
  port: 7777
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

resilience4j:
  bulkhead:
    instances:
      globalBulkhead:
        max-concurrent-calls: 5
        max-wait-duration: 500ms

spring:  
#  kafka:
#    bootstrap-servers: localhost:9092
  application:
    name: quitstart
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config:1234@localhost:9393
# 주석처리 한 부분은 config server의 prperties에 존재
#  boot:
#    admin:
#      client:
#        url: http://localhost:9000/adminPage
##        username: admin
##        password: admin

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mariadb.sql
  datasource-meta:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://neobns.com:13306/db1
    username: POC_USER
    password: neobns1!
  datasource-data:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://neobns.com:13306/db2
    username: POC_USER
    password: neobns1!
  datasource-target:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://neobns.com:13306/db3
    username: POC_USER
    password: neobns1!
#  datasource-spiderdb:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@3.35.132.32:1521/xe
#    username: system
#    password: neobns
      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
#      host: 3.35.132.32
#      port: 6379
#      password: neobns1!
      host: localhost
      port: 6379
      password: 

# 주석처리 한 부분은 config server의 prperties에 존재
#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka:1234@localhost:8761/eureka
      
#management:
#  httpexchanges:
#    recording:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      base-path: /actuator
#  endpoint:
#    metrics:
#      enabled: true
#    health:
#      show-details: always
#    prometheus:
#      enabled: true
#    env:
#      enabled: true
#    busrefresh:
#      enabled: true
#  info:
#    env:
#      enabled: true
#  metrics:
#    enable:
#      hikaricp: true
