spring:
  application:
    name: flowcontrol
  datasource:
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
mybatis:
  mapper-locations: classpath:mappers/*.xml
