server:
  port: 17000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  boot:
    admin:
      client:
        url: http://localhost:19000/admin

management:
  httpexchanges:
    recording:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator  
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true  
    env:
      enabled: true
    busrefresh:
      enabled: true      
  info:
    env:
      enabled: true
  metrics:
    enable:
      hikaricp: true    

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG

