server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: BootGatewayServer
  cloud:
    gateway:
      routes:
        - id: quitstart
          uri: lb://QUITSTART
          predicates:
            - Path=/quitstart/**
          filters:
            - RewritePath=/quitstart/(?<path>.*), /$\{path}
        - id: transfer
          uri: lb://transfer
          predicates:
            - Path=/transfer/**
          filters:
            - RewritePath=/transfer/(?<path>.*), /$\{path}
