spring:
  application:
    name: accounts
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config:1234@localhost:9393
  datasource: 
    url: jdbc:mysql://localhost:3306/db2
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    
    show-sql: true
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:1234@localhost:8761/eureka