spring:
  application:
    name: kafkaConsumerProject
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
      group-id: example-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
server:
  port: 8788
