{
 "title": "Spring Cloud Gateway",
 "description": "Spring Cloud Gateway Dashboard provided by: https://github.com/spring-cloud/spring-cloud-gateway",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gatewayService",
    "label": "Gateway Service",
    "query": "label_values(gateway_requests_seconds_count,job)"
   },
   {
    "name": "routeId",
    "label": "Route Id",
    "query": "label_values(gateway_requests_seconds_count,routeId)"
   }
  ]
 },
 "panels": [
  { "title": "SLOW QUERY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 1, "y": 1 } },
  { "title": "ERROR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 1, "y": 10 } },
  { "title": "Total Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{job=~\"gateway\"})"
    }
   ]
  },
  {
   "title": "Total Successful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=~\"gateway\"})"
    }
   ]
  },
  {
   "title": "Total Unsuccessful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=~\"gateway\"})"
    }
   ]
  },
  { "title": "Request Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$routeId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"quitstart\", job=~\"gateway\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"quitstart\", job=~\"gateway\"}",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"transfer\", job=~\"gateway\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"transfer\", job=~\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Successful API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$routeId Success API Gateway Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"quitstart\", job=~\"gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    },
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"transfer\", job=~\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Unsuccessful API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$routeId Unsuccessful GW Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"quitstart\", job=~\"gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    },
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"transfer\", job=~\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API / HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "$routeId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeId=~\"quitstart\", job=~\"gateway\"}) by (job, status)",
     "legendFormat": "{{ job }} / {{ status }}"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeId=~\"transfer\", job=~\"gateway\"}) by (job, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=~\"gateway\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "process_cpu_usage{job=~\"quick_start\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_usage{job=~\"transfer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"gateway\"}) by (job, instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"quitstart\"}) by (job, instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"transfer\"}) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=~\"gateway\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "jvm_threads_live_threads{job=~\"quitstart\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_live_threads{job=~\"transfer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total/jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}