{
 "title": "Spring Cloud Gateway",
 "description": "Spring Cloud Gateway Dashboard provided by: https://github.com/spring-cloud/spring-cloud-gateway",
 "time": { "from": "2024-12-16T20:31:39.616Z", "to": "2024-12-17T09:02:55.603Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gatewayService",
    "label": "Gateway Service",
    "query": "label_values(gateway_requests_seconds_count,job)"
   },
   {
    "name": "routeId",
    "label": "Route Id",
    "query": "label_values(gateway_requests_seconds_count,routeId)"
   }
  ]
 },
 "panels": [
  { "title": "SLOW QUERY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "평균 요청 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum) / sum by (job)(http_client_requests_seconds_count)",
     "legendFormat": "평균 HTTP 요청 처리 시간({{job}})"
    },
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum{method=\"GET\"}) /\r\nsum by (job)(http_client_requests_seconds_count{method=\"GET\"})",
     "legendFormat": "GET 전체({{job}})"
    },
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum{method=\"POST\"}) /\r\nsum by (job)(http_client_requests_seconds_count{method=\"POST\"})",
     "legendFormat": "POST 전체({{job}})"
    }
   ]
  },
  {
   "title": "느린 쿼리 단위시간 당 발생 여부",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job) (avg_over_time(http_client_requests_seconds_sum[1s])) \r\n/ \r\nsum by (job) (avg_over_time(http_client_requests_seconds_count[1s]))\r\n> bool 0.005",
     "legendFormat": "1초 초과 요청 여부({{job}})"
    }
   ]
  },
  { "title": "ERROR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "평균 에러 발생 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 18 },
   "targets": [
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum{status=~\"2..\"}) / \r\nsum by (job)(http_client_requests_seconds_count{status=~\"2..\"})",
     "legendFormat": "gateway 정상({{job}})"
    },
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum{status=~\".*ERROR|4..|5..\"}) / \r\nsum by (job)(http_client_requests_seconds_count{status=~\".*ERROR|4..|5..\"})",
     "legendFormat": "gateway 에러({{job}})"
    }
   ]
  },
  { "title": "총 처리량", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "게이트웨이 총 요청 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(spring_cloud_gateway_requests_seconds_count)",
     "legendFormat": "게이트웨이 통한 총 요청 수{{job}}"
    }
   ]
  },
  {
   "title": "게이트웨이 총 성공 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=~\"gateway\"})",
     "legendFormat": "게이트웨이 총 성공 리퀘스트 수{{label_name}}"
    }
   ]
  },
  {
   "title": "게이트웨이 실패 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\"})",
     "legendFormat": "게이트웨이 실패 수{{job}}"
    }
   ]
  },
  { "title": "리퀘스트 수행 시간", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$routeId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "sum by (job, routeId) (rate(spring_cloud_gateway_requests_seconds_sum[1m]))\r\n/\r\nsum by (job, routeId) (rate(spring_cloud_gateway_requests_seconds_count[1m]))",
     "legendFormat": "평균 요청 처리 시간({{job}} : {{routeId}})"
    },
    {}
   ]
  },
  { "title": "API 요청", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "전체 API 게이트웨이 요청",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "sum by (job, routeId) (rate(spring_cloud_gateway_requests_seconds_count[1m]))",
     "legendFormat": "분당 HTTP 요청 수({{ job }} - {{ routeId }})"
    }
   ]
  },
  {
   "title": "성공 API 요청",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 39 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "sum by (job, routeId) (\r\n    spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\"}\r\n)",
     "legendFormat": "성공 요청 수 ({{ job }} - {{ routeId}})"
    }
   ]
  },
  {
   "title": "실패 API 요청",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 39 },
   "targets": [
    {
     "expr": "sum by (job, routeId) (\r\n    spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\"}\r\n)",
     "legendFormat": "실패 요청 수 ({{ job }} - {{ routeId}})"
    }
   ]
  },
  { "title": "API / HTTP 상태", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "$routeId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "sum by (job, routeId, status) (spring_cloud_gateway_requests_seconds_count)",
     "legendFormat": "요청 처리 횟수({{ job }} / {{routeId}} / {{ status }})"
    }
   ]
  }
 ]
}