{
 "title": "애플리케이션 모니터링 대시보드",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "애플리케이션 모니터링 요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "애플리케이션 실행 시간",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "애플리케이션 시작 시간",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap 사용량",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap 사용량",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Thread 상태 모니터링",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "애플리케이션 지연/에러 모니터링", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "페이지 응답 소요 시간",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "data_db",
     "rawSql": "select\r\n  cast(timestmp as unsigned) as \"시간(yyyyMMddhhmmss)\",\r\n  trace_id as \"추적ID\",\r\n  (execute_result*1) as \"소요시간(ms)\",\r\n  caller_class as \"호출\",\r\n  caller_method as \"호출상세\"\r\nfrom db2.logging_event\r\nwhere\r\n  logger_name = \"TRACE\"\r\n  and execute_result is not null\r\n  and timestmp > DATE_SUB(NOW(), INTERVAL 2 DAY)\r\n  and caller_method IN (\"GET\", \"POST\", \"PUT\", \"DELETE\")\r\norder by timestmp desc;"
    }
   ]
  },
  {
   "title": "쿼리 실행 소요 시간",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "dataset": "db2",
     "rawSql": "select\r\n  cast(timestmp as unsigned) as \"시간(yyyyMMddhhmmss)\",\r\n  trace_id as \"추적ID\",\r\n  (execute_result*1) as \"소요시간(ms)\",\r\n  caller_class as \"호출\",\r\n  caller_method as \"호출상세\"\r\nfrom db2.logging_event\r\nwhere\r\n  logger_name = \"TRACE\"\r\n  and execute_result is not null\r\n  and timestmp > DATE_SUB(NOW(), INTERVAL 2 DAY)\r\n  and caller_class = \"SQL\"\r\norder by timestmp desc;"
    }
   ]
  },
  { "title": "SLOW/ERROR 로그 조회", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "SLOW 로그",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "data_db",
     "rawSql": "SELECT\r\n  timestmp AS \"시간\",\r\n  trace_id AS \"추적ID\",\r\n  caller_class AS \"호출\",\r\n  caller_method AS \"호출상세\",\r\n  execute_result AS \"결과\"\r\nfrom db2.logging_slow\r\norder by timestmp desc;"
    }
   ]
  },
  {
   "title": "ERROR 로그",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataset": "data_db",
     "rawSql": "SELECT\r\n  timestmp AS \"시간\",\r\n  trace_id AS \"추적ID\",\r\n  caller_class AS \"호출\",\r\n  caller_method AS \"호출상세\",\r\n  execute_result AS \"결과\"\r\nfrom db2.logging_error\r\norder by timestmp desc;"
    }
   ]
  },
  { "title": "전체 로그 조회", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "전체 로그 조회",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "dataset": "db2",
     "rawSql": "SELECT\r\n  timestmp AS \"시간\",\r\n  trace_id AS \"추적ID\",\r\n  caller_class AS \"호출\",\r\n  caller_method AS \"호출상세\",\r\n  logger_name AS \"종류\",\r\n  execute_result AS \"결과\"\r\nFROM db2.logging_event\r\nORDER BY timestmp desc\r\nLIMIT 50"
    }
   ]
  }
 ]
}