{
 "title": "어플리케이션 모니터링",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "어플리케이션 상태 요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "어플리케이션 실행 시간",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(process_uptime_seconds{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "어플리케이션 시작 시간",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap 사용량",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum by (job)(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Non-Heap 사용량",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum by (job)(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Gateway API 모니터링", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "전체 API 게이트웨이 요청",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job, routeId) (rate(spring_cloud_gateway_requests_seconds_count[1m]))",
     "legendFormat": "분당 HTTP 요청 수({{ job }} - {{ routeId }})"
    }
   ]
  },
  {
   "title": "성공 API 요청",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job, routeId) (\r\n    spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\"}\r\n)",
     "legendFormat": "성공 요청 수 ({{ job }} - {{ routeId}})"
    }
   ]
  },
  {
   "title": "실패 API 요청",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job, routeId) (\r\n    spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\"}\r\n)",
     "legendFormat": "실패 요청 수 ({{ job }} - {{ routeId}})"
    }
   ]
  },
  { "title": "Gateway 요청 모니터링", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "평균 요청 시간",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum) / sum by (job)(http_client_requests_seconds_count)",
     "legendFormat": "평균 HTTP 요청 처리 시간({{job}})"
    },
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum{method=\"GET\"}) /\r\nsum by (job)(http_client_requests_seconds_count{method=\"GET\"})",
     "legendFormat": "GET 전체({{job}})"
    },
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum{method=\"POST\"}) /\r\nsum by (job)(http_client_requests_seconds_count{method=\"POST\"})",
     "legendFormat": "POST 전체({{job}})"
    }
   ]
  },
  {
   "title": "느린 요청 단위시간 당 발생 여부",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by (job) (avg_over_time(http_client_requests_seconds_sum[1s])) \r\n/ \r\nsum by (job) (avg_over_time(http_client_requests_seconds_count[1s]))\r\n> bool 0.005",
     "legendFormat": "1초 초과 요청 여부({{job}})"
    }
   ]
  },
  {
   "title": "평균 에러 발생 시간",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum{status=~\"2..\"}) / \r\nsum by (job)(http_client_requests_seconds_count{status=~\"2..\"})",
     "legendFormat": "gateway 정상({{job}})"
    },
    {
     "expr": "sum by (job)(http_client_requests_seconds_sum{status=~\".*ERROR|4..|5..\"}) / \r\nsum by (job)(http_client_requests_seconds_count{status=~\".*ERROR|4..|5..\"})",
     "legendFormat": "gateway 에러({{job}})"
    }
   ]
  },
  { "title": "I/O 개요", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job)(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "요청횟수({{job}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "에러 횟수({{job}})"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job)(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum by (job)(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP 평균({{job}})"
    },
    {
     "expr": "max by (job)(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP 최대({{job}})"
    }
   ]
  },
  {
   "title": "JVM 메모리",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (job) (jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "사용 메모리({{job}})"
      },
      {
       "expr": "sum by (job)(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "할당 메모리({{job}})"
      },
      {
       "expr": "sum by (job)(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "최대 메모리({{job}})"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (job)(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "사용 메모리({{job}})"
      },
      {
       "expr": "sum by (job)(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "할당 메모리({{job}})"
      },
      {
       "expr": "sum by (job)(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "최대 메모리({{job}})"
      }
     ]
    },
    {
     "title": "JVM 메모리 총합",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (job)(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "사용 메모리({{job}})"
      },
      {
       "expr": "sum by (job)(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "할당 메모리({{job}})"
      },
      {
       "expr": "sum by (job)(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "최대 메모리({{job}})"
      }
     ]
    }
   ]
  },
  { "title": "JVM 기타", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "시스템({{job}})"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "프로세스({{job}})"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[15m])",
     "legendFormat": "프로세스 평균({{job}})"
    }
   ]
  },
  {
   "title": "부하",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "시스템 부하({{job}})"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "시스템 CPU 코어 수({{job}})"
    }
   ]
  },
  {
   "title": "스레드",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "활성 스레드 수({{job}})"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "데몬 스레드 수({{job}})"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "최대 스레드 수({{job}})"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "생성 스레드 수({{job}})"
    }
   ]
  },
  {
   "title": "Thread 상태 모니터링",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "스레드 수({{job}} : {{state}})"
    }
   ]
  },
  {
   "title": "로그 이벤트",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "로그 이벤트 수({{job}}-{{level}})"
    }
   ]
  },
  {
   "title": "어플리케이션 지연/에러 모니터링",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "페이지 응답 소요 시간",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "dataset": "data_db",
       "rawSql": "select\r\n  cast(timestmp as unsigned) as \"시간(yyyyMMddhhmmss)\",\r\n  trace_id as \"추적ID\",\r\n  (execute_result*1) as \"소요시간(ms)\",\r\n  caller_class as \"호출\",\r\n  caller_method as \"호출상세\"\r\nfrom db2.logging_event\r\nwhere\r\n  logger_name = \"TRACE\"\r\n  and execute_result is not null\r\n  and timestmp > DATE_SUB(NOW(), INTERVAL 2 DAY)\r\n  and caller_method IN (\"GET\", \"POST\", \"PUT\", \"DELETE\")\r\norder by timestmp desc;"
      }
     ]
    },
    {
     "title": "쿼리 실행 소요 시간",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "dataset": "db2",
       "rawSql": "select\r\n  cast(timestmp as unsigned) as \"시간(yyyyMMddhhmmss)\",\r\n  trace_id as \"추적ID\",\r\n  (execute_result*1) as \"소요시간(ms)\",\r\n  caller_class as \"호출\",\r\n  caller_method as \"호출상세\"\r\nfrom db2.logging_event\r\nwhere\r\n  logger_name = \"TRACE\"\r\n  and execute_result is not null\r\n  and timestmp > DATE_SUB(NOW(), INTERVAL 2 DAY)\r\n  and caller_class = \"SQL\"\r\norder by timestmp desc;"
      }
     ]
    },
    {
     "title": "SLOW 로그",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "dataset": "data_db",
       "rawSql": "SELECT\r\n  timestmp AS \"시간\",\r\n  trace_id AS \"추적ID\",\r\n  caller_class AS \"호출\",\r\n  caller_method AS \"호출상세\",\r\n  execute_result AS \"결과\"\r\nfrom db2.logging_slow\r\norder by timestmp desc;"
      }
     ]
    },
    {
     "title": "ERROR 로그",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "dataset": "data_db",
       "rawSql": "SELECT\r\n  timestmp AS \"시간\",\r\n  trace_id AS \"추적ID\",\r\n  caller_class AS \"호출\",\r\n  caller_method AS \"호출상세\",\r\n  execute_result AS \"결과\"\r\nfrom db2.logging_error\r\norder by timestmp desc;"
      }
     ]
    },
    {
     "title": "전체 로그 조회",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "dataset": "db2",
       "rawSql": "SELECT\r\n  timestmp AS \"시간\",\r\n  trace_id AS \"추적ID\",\r\n  caller_class AS \"호출\",\r\n  caller_method AS \"호출상세\",\r\n  logger_name AS \"종류\",\r\n  execute_result AS \"결과\"\r\nFROM db2.logging_event\r\nORDER BY timestmp desc\r\nLIMIT 50"
      }
     ]
    }
   ]
  }
 ]
}