@startuml
http://localhost:8000/quitstart/item?id=1 -> com.example.neobns.controller.QuickController : GET
com.example.neobns.controller.QuickController -> com.example.neobns.service.QuickService : getItem
com.example.neobns.service.QuickService -> com.example.neobns.mapper.QuickMapper : getItemById
com.example.neobns.mapper.QuickMapper -> SQL : findById
SQL -> com.example.neobns.mapper.QuickMapper : SELECT * FROM item WHERE id = ?
com.example.neobns.mapper.QuickMapper -> com.example.neobns.service.QuickService : findById
com.example.neobns.service.QuickService -> com.example.neobns.controller.QuickController : getItemById
com.example.neobns.controller.QuickController -> http://localhost:8000/quitstart/item?id=1 : getItem
http://localhost:8000/quitstart/item?id=1 -> http://localhost:8000/quitstart/item?id=1 : GET
@enduml