spring:
  application:
    name: accounts
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config:1234@localhost:9393
  datasource: 
    url: jdbc:mysql://localhost:3306/db2
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:19000/admin  
        
management:
  httpexchanges:
    recording:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true  
    env:
      enabled: true
    busrefresh:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    enable:
      hikaricp: true
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:1234@localhost:8761/eureka