spring:
  application:
    name: quitstart
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config:1234@localhost:9393
  boot:
    admin:
      client:
        url: http://localhost:9000

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.1.70:3307/db1
    username: root
    password: 1234
  datasource-data:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.1.70:3307/db2
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    