spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: quitstart
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config:1234@localhost:9393
  boot:
    admin:
      client:
        url: http://localhost:9000
#        username: admin
#        password: admin

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 1234
  datasource-data:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2
    username: root
    password: 1234
  datasource-target:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        session_factory:
          statement_inspector: com.example.neobns.logging.common.JPASqlStatementInspector
  data:
    redis:
      host: localhost
      # 레디스 돌릴 서버 호스트로 수정할 것
      # sudo vim /etc/redis/redis.conf
      # # 1) 모든 IP에서 접속 허용
      # bind 0.0.0.0
      # 2) 외부 접속 허용 (권장 비밀번호 설정)
      # requirepass your_password
      # 3) 포트 설정 (기본값 6379)
      # port 6379
      port: 6379
      password: 

    
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:1234@localhost:8761/eureka
      
management:
  httpexchanges:
    recording:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true  
    env:
      enabled: true
    busrefresh:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    enable:
      hikaricp: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
