{
 "title": "JVM (Micrometer)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
     "legendFormat": "CPU time spent on GC"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_heap",
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "repeat": "jvm_memory_pool_nonheap",
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "$jvm_buffer_pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "repeat": "jvm_buffer_pool",
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "buffers"
    }
   ]
  }
 ]
}