{
 "title": "Spring Cloud Gateway",
 "description": "Spring Cloud Gateway Dashboard provided by: https://github.com/spring-cloud/spring-cloud-gateway",
 "time": { "from": "2024-11-26T22:03:53.842Z", "to": "2024-11-28T19:13:30.262Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gatewayService",
    "label": "Gateway Service",
    "query": "label_values(gateway_requests_seconds_count,job)"
   },
   {
    "name": "routeId",
    "label": "Route Id",
    "query": "label_values(gateway_requests_seconds_count,routeId)"
   }
  ]
 },
 "panels": [
  { "title": "SLOW QUERY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "평균 요청 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_sum{job=\"gateway\"}) / sum(http_client_requests_seconds_count{job=\"gateway\"})",
     "legendFormat": "gateway"
    },
    {
     "expr": "sum(http_client_requests_seconds_sum{job=\"quick_start\"}) / sum(http_client_requests_seconds_sum{job=\"quick_start\"})",
     "legendFormat": "quick start"
    },
    {
     "expr": "sum(http_client_requests_seconds_sum{job=\"transfer\"}) / sum(http_client_requests_seconds_count{job=\"transfer\"})",
     "legendFormat": "transfer"
    },
    {
     "expr": "sum(http_client_requests_seconds_sum{method=\"GET\"}) /\r\nsum(http_client_requests_seconds_count{method=\"GET\"})",
     "legendFormat": "GET 전체"
    },
    {
     "expr": "sum(http_client_requests_seconds_sum{method=\"POST\"}) /\r\nsum(http_client_requests_seconds_count{method=\"POST\"})",
     "legendFormat": "POST 전체"
    }
   ]
  },
  {
   "title": "느린 쿼리 초당 발생 비율",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 9 },
   "targets": [
    {
     "expr": "1 - (sum(rate(prometheus_http_request_duration_seconds_bucket{le=\"1.0\"}[1s])) / sum(rate(prometheus_http_request_duration_seconds_count[1s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (\r\n  sum(rate(prometheus_http_request_duration_seconds_bucket{le=\"1.0\", method=\"GET\"}[1s])) /\r\n  sum(rate(prometheus_http_request_duration_seconds_count{method=\"GET\"}[1s]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (\r\n  sum(rate(prometheus_http_request_duration_seconds_bucket{le=\"1.0\", method=\"POST\"}[1s])) /\r\n  sum(rate(prometheus_http_request_duration_seconds_count{method=\"POST\"}[1s]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1초 초과 요청 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[5m])) - sum(increase(http_request_duration_seconds_bucket{le=\"1.0\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=\"gateway\", method=\"GET\"}[5m])) -\r\nsum(increase(http_request_duration_seconds_bucket{job=\"gateway\", le=\"1.0\", method=\"GET\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ERROR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "평균 에러 발생 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 26 },
   "targets": [
    {
     "expr": "sum(prometheus_http_request_duration_seconds_sum{status=~\"4..|5..\"}) / \r\nsum(prometheus_http_request_duration_seconds_count{status=~\"4..|5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "에러 초당 발생 빈도",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_http_requests_total{status=~\"400\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(prometheus_http_requests_total{status=~\"404\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(prometheus_http_requests_total{status=\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Total Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{job=~\"gateway\"})"
    }
   ]
  },
  {
   "title": "Total Successful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=~\"gateway\"})"
    }
   ]
  },
  {
   "title": "Total Unsuccessful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=~\"gateway\"})"
    }
   ]
  },
  { "title": "Request Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "$routeId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"quitstart\", job=~\"gateway\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"quitstart\", job=~\"gateway\"}",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"transfer\", job=~\"gateway\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"transfer\", job=~\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Successful API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "$routeId Success API Gateway Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 55 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"quitstart\", job=~\"gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    },
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"transfer\", job=~\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Unsuccessful API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "$routeId Unsuccessful GW Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"quitstart\", job=~\"gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    },
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"transfer\", job=~\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API / HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "$routeId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 71 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeId=~\"quitstart\", job=~\"gateway\"}) by (job, status)",
     "legendFormat": "{{ job }} / {{ status }}"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeId=~\"transfer\", job=~\"gateway\"}) by (job, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=~\"gateway\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "process_cpu_usage{job=~\"quick_start\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_usage{job=~\"transfer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"gateway\"}) by (job, instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"quitstart\"}) by (job, instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"transfer\"}) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=~\"gateway\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "jvm_threads_live_threads{job=~\"quitstart\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_live_threads{job=~\"transfer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total/jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}