server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    web-application-type: reactive
  application:
    name: GatewayServer
#  boot:
#    admin:
#      client:
#        url: http://localhost:9000
  cloud:
    gateway:
      forwarded:
        enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: '*' # 허용하려는 헤더
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: quitstart
          uri: lb://quitstart
          predicates:
            - Path=/quitstart/**
            - Method=GET, POST
          filters:
            - RewritePath=/quitstart/(?<path>.*), /$\{path}
            
        - id: quitstart
          uri: lb://quitstart
          predicates:
            - Path=/quitstart/actuator/**
            - Method=GET
          filters:
            - RewritePath=/quitstart/(?<path>.*), /$\{path}
            
        - id: transfer
          uri: lb://transfer
          predicates:
            - Path=/transfer/**
            - Method=GET, POST
          filters:
            - RewritePath=/transfer/(?<path>.*), /$\{path}
            
        - id: transfer
          uri: lb://transfer
          predicates:
            - Path=/transfer/actuator/**
            - Method=GET
          filters:
            - RewritePath=/transfer/(?<path>.*), /$\{path} 

        - id: admin
          uri: lb://adminserver
          predicates:
            - Path=/admin/**
            - Method=GET, POST
          filters:
            - RewritePath=/admin/(?<path>.*), /$\{path}

        # 게이트웨이를 통해서 adminserver의 resource에 접근하기 위해 추가
        - id: admin_resources_route
          uri: lb://adminserver
          predicates:
            - Path=/admin/assets/**
          filters:
            - RewritePath=/admin/(?<path>.*), /$\{path}

#management:
#  httpexchanges:
#    recording:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    jmx:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#  info:
#    env:
#      enabled: true

