

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: GatewayServer
  boot:
    admin:
      client:
        url: http://localhost:9000
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: quitstart
          uri: lb://quitstart
          predicates:
            - Path=/quitstart/**
            - Method=GET, POST
          filters:
            - name: GlobalFilter
            - RewritePath=/quitstart/(?<path>.*), /$\{path}
        - id: transfer
          uri: lb://transfer
          predicates:
            - Path=/transfer/**
            - Method=GET, POST
          filters:
            - RewritePath=/transfer/(?<path>.*), /$\{path}