spring:
  application:
    name: wiremock_service
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/, classpath:/wiremock/mappings/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mariadb://neobns.com:13306/db2?useSSL=false&serverTimezone=Asia/Seoul
    username: POC_USER
    password: neobns1!
    driver-class-name: org.mariadb.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.neobns.wiremock_service
  configuration:
      map-underscore-to-camel-case: true
    
server:
  port: 8889